same_for_all:
  #smcs:            both
  distance_sensor:  dist_sensor
  controller:       aicon
  target_config:    chase
  obstacles:        no_obstacles
  sensor_noise:     huge_dist_o_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_state_config:
  PolarTargetPos:
    indices: [0]
    labels:  [Distance]
    xbounds: [0, 200]
    ybounds: [[[-1, 20]], [[-1, 20]], [[-1, 30]]]

plotting_style_config:
  nosmcs:
    label:     No SMCs
    color:     red      # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid    # dotted, dashed, dashdot
    linewidth: 2
  tri:
    label:     Triangulation
    color:     orange
    linestyle: solid
    linewidth: 2
  div:
    label:     Divergence
    color:     green
    linestyle: solid
    linewidth: 2
  both:
    label:     Triangulation + Divergence
    color:     blue
    linestyle: solid
    linewidth: 2
