same_for_all:
  smcs:             both
  distance_sensor:  no_dist_sensor
  #controller:      aicon
  #moving_target:   stationary_target
  moving_obstacles: stationary_obstacle
  sensor_noise:     small_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  wind:             no_wind
  control:          vel

variations:
  - controller:    aicon
    moving_target: flight_target
  - controller:    aicon
    moving_target: chase_target
  - controller:    manual
    moving_target: flight_target
  - controller:    manual
    moving_target: chase_target

plotting_state_config:
  PolarTargetPos:
    indices: [0]
    labels:  [Distance]
    ybounds: [[[5, 30]], [[-1, 10]], [[-1, 20]]]

plotting_style_config:
  flight_target_aicon:
    label:     AICON control | flight target
    color:     blue     # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid    # dotted, dashed, dashdot
    linewidth: 2
  chase_target_aicon:
    label:     AICON control | chase target
    color:     blue
    linestyle: dashed
    linewidth: 2
  flight_target_manual:
    label:     designed control | flight target
    color:     red
    linestyle: solid
    linewidth: 2
  chase_target_manual:
    label:     designed control | chase target
    color:     red
    linestyle: dashed
    linewidth: 2
