same_for_all:
  smcs:             both
  distance_sensor:  no_dist_sensor
  #controller:      aicon
  #target_config:   stationary
  obstacles:        no_obstacles
  sensor_noise:     small_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - controller:    aicon
    target_config: stationary
  - controller:    aicon
    target_config: sine
  - controller:    manual
    target_config: stationary
  - controller:    manual
    target_config: sine

plotting_state_config:
  PolarTargetPos:
    indices: [0]
    labels:  [Distance]
    xbounds: [0, 200]
    ybounds: [[[5, 30]], [[-1, 10]], [[-1, 20]]]

plotting_style_config:
  stationary_aicon:
    label:     \makebox[1.5cm][l]{AICON} Target Stationary 
    color:     blue     # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid    # dotted, dashed, dashdot
    linewidth: 2
  sine_aicon:
    label:     \makebox[1.5cm][l]{AICON} Target Moves
    color:     blue
    linestyle: dashed
    linewidth: 2
  stationary_manual:
    label:     \makebox[1.5cm][l]{PRC} Target Stationary
    color:     red
    linestyle: solid
    linewidth: 2
  sine_manual:
    label:     \makebox[1.5cm][l]{PRC} Target Moves
    color:     red
    linestyle: dashed
    linewidth: 2
