
same_for_all:
  #smcs:            both
  distance_sensor:  dist_sensor
  controller:       aicon
  target_config:    sine_target
  obstacles:        no_obstacles
  sensor_noise:     small_noise
  observation_loss: dist_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_state_config:
  PolarTargetPos:
    indices: [0]
    labels:  [Distance]
    ybounds: [[[0, 20]], [[-10, 5]], [[-1, 20]]]

plotting_style_config:
  nosmcs:
    label:     No SMCS
    color:     black      # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid      # dotted, dashed, dashdot
    linewidth: 2
  tri:
    label:     Triangulation
    color:     blue
    linestyle: solid
    linewidth: 2
  div:
    label:     Divergence
    color:     green
    linestyle: solid
    linewidth: 2
  both:
    label:     Both
    color:     red
    linestyle: solid
    linewidth: 2
