same_for_all:
  smrs:             both
  distance_sensor:  no_dist_sensor
  obstacles:        no_obstacles
  sensor_noise:     small_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  # From classic_exp1_extended.yaml
  - controller:    aicon
    target_config: stationary
  - controller:    aicon
    target_config: linear
  - controller:    aicon
    target_config: sine
  - controller:    trc
    target_config: stationary
  - controller:    trc
    target_config: linear
  - controller:    trc
    target_config: sine
  # From classic_exp1_targetflightnchase.yaml
  - controller:    aicon
    target_config: flight
  - controller:    aicon
    target_config: chase
  - controller:    trc
    target_config: flight
  - controller:    trc
    target_config: chase


plotting_config:
  exclude_runs: []
  xbounds: [0, 200]

  motion_colors:
    stationary: [darkgoldenrod, gold]
    linear:     [darkslategrey, teal]
    sine:       [indigo, mediumpurple]
    #flight:     [darkred, lightcoral]
    flight:     [navy, cornflowerblue]
    #chase:      [darkgreen, lightgreen]
    chase:      [darkred, lightcoral]
    motion:     [darkblue, lightsteelblue]

  states:
    PolarTargetPos:
      indices:    [0]
      labels:     [Distance]
      ybounds:    [[[0, 30]], [[-1, 10]], [[-1, 20]]]
      boxybounds: [[[0, 17.5]], [[0, 7]], [[0, 7]]]

  style:
    aicon_stationary:
      label:     \makebox[2.0cm][l]{AICON} T stationary
      boxlabel:  $S$
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid
      linewidth: 2
    aicon_linear:
      label:     \makebox[2.0cm][l]{AICON} T linear
      boxlabel:  $L$
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    aicon_sine:
      label:     \makebox[2.0cm][l]{AICON} T sine
      boxlabel:  $W$
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dotted
      linewidth: 2
    aicon_flight:
      label:     \makebox[2.0cm][l]{AICON} T flees from R
      boxlabel:  $F$
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    aicon_chase:
      label:     \makebox[2.0cm][l]{AICON} T chases R
      boxlabel:  $C$
      boxcolor:  thistle
      color:     purple
      linestyle: dashed
      linewidth: 2
    aicon_motion:
      label:     \makebox[2.0cm][l]{AICON} T moves
      boxlabel:  $M$
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    # -----------------------------------------------------
    trc_stationary:
      label:     \makebox[2.0cm][l]{TRC} T stationary
      boxlabel:  $S$
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid
      linewidth: 2
    trc_linear:
      label:     \makebox[2.0cm][l]{TRC} T linear
      boxlabel:  $L$
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    trc_sine:
      label:     \makebox[2.0cm][l]{TRC} T sine
      boxlabel:  $W$
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dotted
      linewidth: 2
    trc_flight:
      label:     \makebox[2.0cm][l]{TRC} T flees from R
      boxlabel:  $F$
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    trc_chase:
      label:     \makebox[2.0cm][l]{TRC} T chases R
      boxlabel:  $C$
      boxcolor:  thistle
      color:     purple
      linestyle: dashed
      linewidth: 2
    trc_motion:
      label:     \makebox[2.0cm][l]{TRC} T moves
      boxlabel:  $M$
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
