same_for_all:
  smcs:             both
  distance_sensor:  dist_sensor
  #controller:      aicon
  target_config:    stationary
  obstacles:        no_obstacles
  #sensor_noise:    small_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - controller:    aicon
    sensor_noise:  small_noise
  - controller:    aicon
    sensor_noise:  neg_dist_o_noise
  - controller:    trc
    sensor_noise:  small_noise
  - controller:    trc
    sensor_noise:  neg_dist_o_noise

plotting_config:
  exclude_runs: []
  xbounds: [0, 200]

  states:
    PolarTargetPos:
      indices:    [0]
      labels:     [Distance]
      ybounds:    [[[8, 26]], [[-1, 8]], [[-1, 8]]]
      absybounds: [[[0, 15]], [[0, 8]], [[0, 5]]]

  style:
    aicon_small_noise:
      label:     \makebox[2.0cm][l]{AICON} no disturbance
      boxlabel:  "AICON\nno disturbance"
      boxcolor:  lightblue
      color:     blue
      linestyle: solid    # dotted, dashed, dashdot
      linewidth: 2
    aicon_neg_dist_o_noise:
      label:     \makebox[2.0cm][l]{AICON} distance sensor offset
      boxlabel:  "AICON\ndistance sensor offset"
      boxcolor:  lightblue
      color:     blue
      linestyle: dashed
      linewidth: 2
    trc_small_noise:
      label:     \makebox[2.0cm][l]{TRC} no disturbance
      boxlabel:  "TRC\nno disturbance"
      boxcolor:  lightcoral
      color:     red
      linestyle: solid
      linewidth: 2
    trc_neg_dist_o_noise:
      label:     \makebox[2.0cm][l]{TRC} distance sensor offset
      boxlabel:  "TRC\ndistance sensor offset"
      boxcolor:  lightcoral
      color:     red
      linestyle: dashed
      linewidth: 2
