same_for_all:
  #smcs:            both
  controller:       aicon
  sensor_noise:     neg_dist_o_noise
  distance_sensor:  dist_sensor
  fv_noise:         no_fv_noise
  # target_config:    sine
  obstacles:        no_obstacles
  observation_loss: no_obs_loss
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs:          nosmcs
    target_config: stationary
  - smcs:          tri
    target_config: stationary
  - smcs:          div
    target_config: stationary
  - smcs:          both
    target_config: stationary
  - smcs:          nosmcs
    target_config: linear
  - smcs:          tri
    target_config: linear
  - smcs:          div
    target_config: linear
  - smcs:          both
    target_config: linear
  - smcs:          nosmcs
    target_config: sine
  - smcs:          tri
    target_config: sine
  - smcs:          div
    target_config: sine
  - smcs:          both
    target_config: sine
  - smcs:          nosmcs
    target_config: flight
  - smcs:          tri
    target_config: flight
  - smcs:          div
    target_config: flight
  - smcs:          both
    target_config: flight
  - smcs:          nosmcs
    target_config: chase
  - smcs:          tri
    target_config: chase
  - smcs:          div
    target_config: chase
  - smcs:          both
    target_config: chase

plotting_config:
  exclude_runs: []
  xbounds: [0, 200]

  states:
    PolarTargetPos:
      indices: [0]
      labels:  [Distance]
      ybounds: [[[0, 30]], [[-5, 10]], [[0, 15]]]
      absybounds: [[[0, 20]], [[0, 20]], [[0, 20]]]
      boxybounds: [[[0, 7]], [[0, 6]], [[0, 9]]]
  style:
    nosmcs_stationary:
      #label:     \makebox[2.5cm][l]{No SMRs} T stat.
      label:     No SMRs $\mid$ T stat.
      boxlabel:  S
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid    # dotted, dashed, dashdot
      linewidth: 2
    nosmcs_linear:
      #label:     \makebox[2.5cm][l]{No SMRs} T linear
      label:     No SMRs $\mid$ T linear
      boxlabel:  L
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    nosmcs_sine:
      #label:     \makebox[2.5cm][l]{No SMRs} T sine
      label:     No SMRs $\mid$ T sine
      boxlabel:  W
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dashed
      linewidth: 2
    nosmcs_flight:
      #label:     \makebox[2.5cm][l]{No SMRs} T flight
      label:     No SMRs $\mid$ T flight
      boxlabel:  F
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    nosmcs_chase:
      #label:     \makebox[2.5cm][l]{No SMRs} T chase
      label:     No SMRs $\mid$ T chase
      boxlabel:  C
      boxcolor:  thistle
      color:     purple
      linestyle: dotted
      linewidth: 2
    nosmcs_motion:
      label:     No SMRs $\mid$ T moves
      boxlabel:  M
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    # -----------------------------------------------------
    tri_stationary:
      #label:     \makebox[2.5cm][l]{Tri.} T stat.
      label:     Tri $\mid$ T stat.
      boxlabel:  S
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid
      linewidth: 2
    tri_linear:
      #label:     \makebox[2.5cm][l]{Tri.} T linear
      label:     Tri $\mid$ T linear
      boxlabel:  L
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    tri_sine:
      #label:     \makebox[2.5cm][l]{Tri.} T sine
      label:     Tri $\mid$ T sine
      boxlabel:  W
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dashed
      linewidth: 2
    tri_flight:
      #label:     \makebox[2.5cm][l]{Tri.} T flight
      label:     Tri $\mid$ T flight
      boxlabel:  F
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    tri_chase:
      #label:     \makebox[2.5cm][l]{Tri.} T chase
      label:     Tri $\mid$ T chase
      boxlabel:  C
      boxcolor:  thistle
      color:     purple
      linestyle: dotted
      linewidth: 2
    tri_motion:
      label:     Tri $\mid$ T moves
      boxlabel:  M
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    # -----------------------------------------------------
    div_stationary:
      #label:     \makebox[2.5cm][l]{Div.} T stat.
      label:     Div $\mid$ T stat.
      boxlabel:  S
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid
      linewidth: 2
    div_linear:
      #label:     \makebox[2.5cm][l]{Div.} T linear
      label:     Div $\mid$ T linear
      boxlabel:  L
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    div_sine:
      #label:     \makebox[2.5cm][l]{Div.} T sine
      label:     Div $\mid$ T sine
      boxlabel:  W
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dashed
      linewidth: 2
    div_flight:
      #label:     \makebox[2.5cm][l]{Div.} T flight
      label:     Div $\mid$ T flight
      boxlabel:  F
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    div_chase:
      #label:     \makebox[2.5cm][l]{Div.} T chase
      label:     Div $\mid$ T chase
      boxlabel:  C
      boxcolor:  thistle
      color:     purple
      linestyle: dotted
      linewidth: 2
    div_motion:
      label:     Div $\mid$ T moves
      boxlabel:  M
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    # -----------------------------------------------------
    both_stationary:
      #label:     \makebox[2.5cm][l]{Tri. + Div.} T stat.
      label:     Tri+Div $\mid$ T stat.
      boxlabel:  S
      boxcolor:  lightcoral
      color:     darkred
      linestyle: solid
      linewidth: 2
    both_linear:
      #label:     \makebox[2.5cm][l]{Tri. + Div.} T linear
      label:     Tri+Div $\mid$ T linear
      boxlabel:  L
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
    both_sine:
      #label:     \makebox[2.5cm][l]{Tri. + Div.} T sine
      label:     Tri+Div $\mid$ T sine
      boxlabel:  W
      boxcolor:  lightblue
      color:     darkblue
      linestyle: dashed
      linewidth: 2
    both_flight:
      #label:     \makebox[2.5cm][l]{Tri. + Div.} T flight
      label:     Tri+Div $\mid$ T flight
      boxlabel:  F
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: dashdot
      linewidth: 2
    both_chase:
      #label:     \makebox[2.5cm][l]{Tri. + Div.} T chase
      label:     Tri+Div $\mid$ T chase
      boxlabel:  C
      boxcolor:  thistle
      color:     purple
      linestyle: dotted
      linewidth: 2
    both_motion:
      label:     Tri+Div $\mid$ T moves
      boxlabel:  M
      boxcolor:  lightgreen
      color:     darkgreen
      linestyle: dashed
      linewidth: 2
