same_for_all:
  #smcs:            both
  distance_sensor:  dist_sensor
  controller:       aicon
  target_config:    sine
  obstacles:        no_obstacles
  sensor_noise:     small_noise
  observation_loss: dist_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_config:
  exclude_runs: []
  xbounds: [0, 300]

  states:
    PolarTargetPos:
      indices: [0]
      labels:  [Distance]
      ybounds: [[[0, 30]], [[-5, 10]], [[0, 15]]]
      absybounds: [[[0, 20]], [[0, 20]], [[0, 20]]]
      boxybounds: [[[0, 5]], [[0, 5]], [[0, 7]]]

  style:
    nosmcs:
      label:     No SMCs
      boxlabel:  No SMCs
      boxcolor:  lightcoral
      color:     red
      linestyle: solid    # dotted, dashed, dashdot
      linewidth: 2
    tri:
      label:     Triangulation
      boxlabel:  T
      boxcolor:  lightgreen
      color:     green
      linestyle: solid
      linewidth: 2
    div:
      label:     Divergence
      boxlabel:  D
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: solid
      linewidth: 2
    both:
      label:     Triangulation + Divergence
      boxlabel:  T+D
      boxcolor:  lightblue
      color:     blue
      linestyle: solid
      linewidth: 2
