same_for_all:
  #smcs:            both
  distance_sensor:  dist_sensor
  controller:       aicon
  target_config:    sine
  obstacles:        no_obstacles
  sensor_noise:     small_noise
  observation_loss: no_obs_loss
  fv_noise:         no_fv_noise
  desired_distance: 10
  start_distance:   0
  wind:             light_wind
  control:          acc

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_config:
  exclude_runs: []

  states:
    PolarTargetPos:
      indices: [0]
      labels:  [Distance]
      xbounds: [0, 500]
      ybounds: [[[-1, 30]], [[-5, 30]], [[-1, 15]]]

  style:
    nosmcs:
      label:     No SMCs
      boxcolor:  lightcoral
      color:     red
      linestyle: solid    # dotted, dashed, dashdot
      linewidth: 2
    tri:
      label:     T
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: solid
      linewidth: 2
    div:
      label:     D
      boxcolor:  lightgreen
      color:     green
      linestyle: solid
      linewidth: 2
    both:
      label:     T+D
      boxcolor:  lightblue
      color:     blue
      linestyle: solid
      linewidth: 2
