same_for_all:
  # smcs: config.smcs.both
  controller:       aicon
  sensor_noise:     neg_dist_o_noise
  distance_sensor:  dist_sensor
  fv_noise:         no_fv_noise
  target_config:    stationary
  obstacles:        no_obstacles
  observation_loss: no_obs_loss
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_config:
  exclude_runs: []
  xbounds: [0, 200]

  states:
    PolarTargetPos:
      indices: [0]
      labels:  [Distance]
      ybounds: [[[8, 15]], [[0, 5]], [[0, 5]]]

  style:
    nosmcs:
      label:     No SMCs
      boxcolor:  lightcoral
      color:     red
      linestyle: solid    # dotted, dashed, dashdot
      linewidth: 2
    tri:
      label:     T
      boxcolor:  peachpuff
      color:     darkorange
      linestyle: solid
      linewidth: 2
    div:
      label:     D
      boxcolor:  lightgreen
      color:     green
      linestyle: solid
      linewidth: 2
    both:
      label:     T+D
      boxcolor:  lightblue
      color:     blue
      linestyle: solid
      linewidth: 2
