same_for_all:
  # smcs: config.smcs.both
  control:          aicon
  sensor_noise:     dist_offset_noise
  distance_sensor:  dist_sensor
  fv_noise:         no_fv_noise
  moving_target:    sine_target
  observation_loss: no_obs_loss
  desired_distance: 5
  wind:             no_wind

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_config:
  nosmcs:
    label:     No SMCs
    color:     red      # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid    # dotted, dashed, dashdot
    linewidth: 2
  tri:
    label:     Triangulation
    color:     green
    linestyle: solid
    linewidth: 2
  div:
    label:     Divergence
    color:     orange
    linestyle: solid
    linewidth: 2
  both:
    label:     Triangulation + Divergence
    color:     blue
    linestyle: solid
    linewidth: 2
