same_for_all:
  # smcs: config.smcs.both
  controller:       aicon
  sensor_noise:     neg_dist_o_noise
  distance_sensor:  dist_sensor
  fv_noise:         no_fv_noise
  moving_target:    sine_target
  moving_obstacles: stationary_obstacle
  observation_loss: no_obs_loss
  desired_distance: 10
  start_distance:   10
  wind:             no_wind
  control:          vel

variations:
  - smcs: nosmcs
  - smcs: tri
  - smcs: div
  - smcs: both

plotting_state_config:
  PolarTargetPos:
    indices: [0]
    labels:  [Distance]
    ybounds: [[[10, 20]], [[2, 7]], [[1, 4]]]

plotting_style_config:
  nosmcs:
    label:     No SMCs
    color:     red      # red, green, blue, cyan, magenta, yellow, black, white
    linestyle: solid    # dotted, dashed, dashdot
    linewidth: 2
  tri:
    label:     Triangulation
    color:     green
    linestyle: solid
    linewidth: 2
  div:
    label:     Divergence
    color:     orange
    linestyle: solid
    linewidth: 2
  both:
    label:     Both
    color:     blue
    linestyle: solid
    linewidth: 2
